# Generated by Django 5.0.6 on 2024-07-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('date_start', models.DateTimeField(verbose_name='تاريخ البدء')),
                ('date_end', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal')], default='normal', max_length=6, verbose_name='الأولوية')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'الإشعار',
                'verbose_name_plural': 'الإشعارات',
            },
        ),
    ]
