# Generated by Django 5.0.6 on 2024-07-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_notification_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
    ]
