# Generated by Django 5.0.6 on 2024-07-04 04:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='logo',
            field=models.ImageField(blank=True, default=accounts.models.default_logo, null=True, upload_to='accounts/logos/', verbose_name='الشعار'),
        ),
    ]
