# Generated by Django 5.0.6 on 2024-07-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='social_icons/', verbose_name='الأيقونة'),
        ),
    ]
