# Generated by Django 5.0.6 on 2024-07-06 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name=' التليفون')),
                ('mail', models.EmailField(max_length=255, verbose_name='الايميل')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksplaces.library', verbose_name='المكتبة')),
            ],
            options={
                'verbose_name': 'وسيلة تواصل',
                'verbose_name_plural': 'وسائل التواصل',
            },
        ),
    ]
