# Generated by Django 5.0.6 on 2024-07-04 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='الموقع')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'السنتر',
                'verbose_name_plural': 'السنترات',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'الفصل',
                'verbose_name_plural': 'الفصول',
            },
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'المحافظة',
                'verbose_name_plural': 'المحافظات',
            },
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
                ('scadual', models.DateTimeField(verbose_name='الجدول')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centersplaces.center', verbose_name='السنتر')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centersplaces.class', verbose_name='الفصل')),
            ],
            options={
                'verbose_name': 'التاريخ',
                'verbose_name_plural': 'التواريخ',
            },
        ),
        migrations.AddField(
            model_name='center',
            name='government',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centersplaces.government', verbose_name='المحافظة'),
        ),
    ]
