# Generated by Django 5.0.6 on 2024-07-04 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centersplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name': 'سنتر', 'verbose_name_plural': 'السناتر'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'صف', 'verbose_name_plural': 'الصفوف'},
        ),
        migrations.AlterModelOptions(
            name='dates',
            options={'verbose_name': 'موعد', 'verbose_name_plural': 'المواعيد'},
        ),
        migrations.AlterModelOptions(
            name='government',
            options={'verbose_name': 'محافظة', 'verbose_name_plural': 'المحافظات'},
        ),
        migrations.AlterField(
            model_name='dates',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centersplaces.class', verbose_name='الصف'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='scadual',
            field=models.DateTimeField(verbose_name='الموعد'),
        ),
    ]
