# Generated by Django 5.0.6 on 2024-07-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centersplaces', '0002_alter_center_options_alter_class_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='name',
            field=models.CharField(default='بدون اسم', max_length=255, verbose_name='الاسم'),
        ),
    ]
