# Generated by Django 5.0.6 on 2024-07-06 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centersplaces', '0003_center_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name=' التليفون')),
                ('mail', models.EmailField(max_length=255, verbose_name='الموقع')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centersplaces.center', verbose_name='السنتر')),
            ],
            options={
                'verbose_name': 'وسيلة تواصل',
                'verbose_name_plural': 'وسائل التواصل',
            },
        ),
    ]
