# Generated by Django 5.0.6 on 2024-07-07 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centersplaces', '0005_alter_centercontact_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='scadual',
        ),
        migrations.AddField(
            model_name='dates',
            name='date_day',
            field=models.CharField(choices=[('1', 'الأحد'), ('2', 'الاثنين'), ('3', 'الثلاثاء'), ('4', 'الاربعاء'), ('5', 'الخميس'), ('6', 'الجمعة'), ('7', 'السبت')], default='1', max_length=255, verbose_name='اليوم'),
        ),
        migrations.AddField(
            model_name='dates',
            name='date_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='الساعة'),
        ),
    ]
