# Generated by Django 5.0.6 on 2024-07-07 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centersplaces', '0006_remove_dates_scadual_dates_date_day_dates_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='date_time',
            field=models.TimeField(default=datetime.time(6, 0), verbose_name='الساعة'),
        ),
    ]
